Add Check for unexpected changes in generated files (#1407)
* Add Check for unexpected changes in generated files

add kafka and snmp generated files

* Fix kafka dashboards CI check

* Add to docker-mixin

* Add golang-observ-lib

* Add jvm-observ-lib

* Add windows

* Add process lib

* Add zookeeper

* Add to csp-mixin check

* Fix process-dashboards.json diff

* Regenerate golang

* Regenerate windows

* Update ci

* Update README

* Update snmp Makefile

* Add common Makefile

* Add activemq

* Add apache mixins

* add confluent

* Add docker-mixin

* Add csp-mixin

* Update goruntime

* Update f5

* Update grafana-agent

* Simplify Makefile to use common mixin Makefile

* Add grafana-builder dependency

* Add envoy

* Add harbor

* Add hass-mixin

* Add influx

* Add haproxy

* Add istio

* Add multiple mixins: IBM MQ, Istio, Jaeger, Jenkins, Jira, and JVM

* Update kafka-mixin

* Add multiple mixins: Couchbase, Discourse, Elasticsearch, GitLab, Kubescape, Memcached, Microsoft IIS, Minio, MongoDB (Atlas and standard), MSSQL, and NGINX

* Add Spark mixin

* Add multiple mixins: Node.js, Nomad, OpenLDAP, OpenSearch, OpenStack, OracleDB, PgBouncer, Presto, Python Runtime, RabbitMQ, Rclone, Redis (Enterprise and standard), Ruby, SAP HANA, and Spring Boot

* Add multiple mixins: Supabase, Tensorflow, Traefik, Vault, Velero, Windows, WSO2 Enterprise and Streaming Integrators

* add snmp-mixin

* Remove unrelated links from snmp-mixin

* set editable: false

* Fix jvm

* Update spring

* make fmt camel

* Fix redis mixin linter

* Fix lint for golang

* Update lint for kafka

* update oracle

* Update nomad

* Update haproxy

* update envoy

* Update jaeger

* update ceph linter

* Fix for asterisk

* Fix .lint

* Update oracle

* Fix cilium

* Update install-ci-deps

* Reset minio

* Add .gitattributes

* fix haproxy

* Update gitattributes

* Fix mixin format

* Fix nomad lint

* Fix .lint

* Update makefile

* fix typo in snmp

* Update lint error message

* Add newline

* Update mixtool to main

* Update snmp

* Fix

* Fix snmp

diff --git a/.github/workflows/lint-mixins.yml b/.github/workflows/lint-mixins.yml
--- a/.github/workflows/lint-mixins.yml
+++ b/.github/workflows/lint-mixins.yml
@@ -46,7 +46,7 @@ jobs:
         run: echo '${{ steps.changed-mixins.outputs.all_changed_files }}'
 
   lint-mixin:
-    name: Run Mixtool
+    name: Lint Mixin
     runs-on: ubuntu-latest
     permissions:
       issues: write
@@ -75,8 +75,13 @@ jobs:
 
       - name: Install Mixin dependencies
         working-directory: ./${{ matrix.mixin }}
-        run: jb install
+        run: make build
 
-      - name: Lint Mixin
+      - name: Lint Mixin with Mixtool
         working-directory: ./${{ matrix.mixin }}
         run: mixtool lint mixin.libsonnet
+
+      - name: Check for unexpected changes in generated files
+        working-directory: ./${{ matrix.mixin }}
+        run: "make && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
+
