Merge ci jobs

diff --git a/.github/workflows/test-mixins.yml b/.github/workflows/test-mixins.yml
--- a/.github/workflows/test-mixins.yml
+++ b/.github/workflows/test-mixins.yml
@@ -59,40 +59,6 @@ jobs:
       matrix:
         mixin: ${{ fromJSON(needs.check-for-changed-mixins.outputs.changed-mixins) }}
       fail-fast: false
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.23
-      
-      - name: Install CI dependencies
-        run: make install-ci-deps
-
-      - name: Install Mixin dependencies
-        working-directory: ./${{ matrix.mixin }}
-        run: make build
-
-      - name: Lint Mixin with Mixtool
-        working-directory: ./${{ matrix.mixin }}
-        run: mixtool lint mixin.libsonnet
-
-      - name: Check for unexpected changes in generated files
-        working-directory: ./${{ matrix.mixin }}
-        run: "make && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
-
-  validate-dashboards:
-    name: Validate Mixins Dashboards
-    runs-on: ubuntu-latest
-    needs: [check-for-changed-mixins]
-    strategy:
-      matrix:
-        mixin: ${{ fromJSON(needs.check-for-changed-mixins.outputs.changed-mixins) }}
-      fail-fast: false
     services:
       grafana:
         image: grafana/grafana:11.4.0
@@ -120,7 +86,15 @@ jobs:
         working-directory: ./${{ matrix.mixin }}
         run: make build
 
-      - name: Generate and validate dashboards
+      - name: Lint Mixin with Mixtool
+        working-directory: ./${{ matrix.mixin }}
+        run: mixtool lint mixin.libsonnet
+
+      - name: Check for unexpected changes in generated files
+        working-directory: ./${{ matrix.mixin }}
+        run: "make && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
+
+      - name: Wait for Grafana and validate dashboards
         working-directory: ./${{ matrix.mixin }}
         env:
           GRAFANA_URL: http://localhost:3000
