Update tests

diff --git a/.github/workflows/test-mixins.yml b/.github/workflows/test-mixins.yml
--- a/.github/workflows/test-mixins.yml
+++ b/.github/workflows/test-mixins.yml
@@ -109,7 +109,7 @@ jobs:
         run: make lint
       - name: Check for unexpected changes in generated files
         working-directory: ./${{ matrix.mixin }}
-        run: "make dashboards_out prometheus_alerts.yaml prometheus_rules.yaml && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
+        run: "make -B dashboards_out prometheus_alerts.yaml prometheus_rules.yaml && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
       - name: Wait for Grafana and validate dashboards
         working-directory: ./${{ matrix.mixin }}
         env:
